### ISSUE TITLE
Error during Python "shutdown"

### ISSUE THREAD

**Issue by jeremyschulman** [leopoul/ncclient#38]
On some occasions I see the following error, using ncclient 0.4.2

````shell````
Exception in thread session (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "build/bdist.linux-x86_64/egg/ncclient/transport/ssh.py", line 352, in run
  File "build/bdist.linux-x86_64/egg/ncclient/transport/session.py", line 71, in _dispatch_error
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'
````

I see this when running on an Ubuntu 14.04LTS system.  I do not see this when I run on my MacOS.  Again very sporadic, not sure how to further debug. 

Please advise, thank you!
-- Jeremy

**Comment by leopoul** [comment]
Fixed in latest 0.4.3 version
